export async function seed(knex) {
  // npm run knex seed:run

  // Deletes ALL existing entries
  await knex('environment_deck').del()

  // Inserts seed entries
  const NUM_SUITS = 5
  const NUM_ENV_COLOURS = 5
  const deck = []

    // iterate for every card in the deck
  for (let i = 1; i <= 100; i++) {
    deck.push({
      id: i,
      suit_id: (i % 5) + 1,
      environment_colour_id: (Math.floor((i - 1) / NUM_SUITS) % NUM_ENV_COLOURS) + 1,
    })
  }
  await knex('environment_deck').insert(deck);
}

/*
  await knex('environment_deck').insert([
    { id: 1, suit_id: 1, environment_colour_id: 1 },
    { id: 2, suit_id: 2, environment_colour_id: 2 },
    { id: 3, suit_id: 3, environment_colour_id: 3 },
    { id: 4, suit_id: 4, environment_colour_id: 4 },
    { id: 5, suit_id: 5, environment_colour_id: 5 },
    { id: 6, suit_id: 2, environment_colour_id: 1 },
    { id: 7, suit_id: 3, environment_colour_id: 2 },
    { id: 8, suit_id: 4, environment_colour_id: 3 },
    { id: 9, suit_id: 1, environment_colour_id: 4 },
    { id: 10, suit_id: 5, environment_colour_id: 5 },
    { id: 11, suit_id: 3, environment_colour_id: 1 },
    { id: 12, suit_id: 4, environment_colour_id: 2 },
    { id: 13, suit_id: 1, environment_colour_id: 3 },
    { id: 14, suit_id: 2, environment_colour_id: 4 },
    { id: 15, suit_id: 5, environment_colour_id: 5 },
    { id: 16, suit_id: 4, environment_colour_id: 1 },
    { id: 17, suit_id: 1, environment_colour_id: 2 },
    { id: 18, suit_id: 2, environment_colour_id: 3 },
    { id: 19, suit_id: 3, environment_colour_id: 4 },
    { id: 20, suit_id: 5, environment_colour_id: 5 },
    { id: 21, suit_id: 1, environment_colour_id: 1 },
    { id: 22, suit_id: 2, environment_colour_id: 2 },
    { id: 23, suit_id: 3, environment_colour_id: 3 },
    { id: 24, suit_id: 4, environment_colour_id: 4 },
    { id: 25, suit_id: 5, environment_colour_id: 5 },
    { id: 26, suit_id: 2, environment_colour_id: 1 },
    { id: 27, suit_id: 3, environment_colour_id: 2 },
    { id: 28, suit_id: 4, environment_colour_id: 3 },
    { id: 29, suit_id: 1, environment_colour_id: 4 },
    { id: 30, suit_id: 5, environment_colour_id: 5 },
    { id: 31, suit_id: 3, environment_colour_id: 1 },
    { id: 32, suit_id: 4, environment_colour_id: 2 },
    { id: 33, suit_id: 1, environment_colour_id: 3 },
    { id: 34, suit_id: 2, environment_colour_id: 4 },
    { id: 35, suit_id: 5, environment_colour_id: 5 },
    { id: 36, suit_id: 4, environment_colour_id: 1 },
    { id: 37, suit_id: 1, environment_colour_id: 2 },
    { id: 38, suit_id: 2, environment_colour_id: 3 },
    { id: 39, suit_id: 3, environment_colour_id: 4 },
    { id: 40, suit_id: 5, environment_colour_id: 5 },
    { id: 41, suit_id: 1, environment_colour_id: 1 },
    { id: 42, suit_id: 2, environment_colour_id: 2 },
    { id: 43, suit_id: 3, environment_colour_id: 3 },
    { id: 44, suit_id: 4, environment_colour_id: 4 },
    { id: 45, suit_id: 5, environment_colour_id: 5 },
    { id: 46, suit_id: 2, environment_colour_id: 1 },
    { id: 47, suit_id: 3, environment_colour_id: 2 },
    { id: 48, suit_id: 4, environment_colour_id: 3 },
    { id: 49, suit_id: 1, environment_colour_id: 4 },
    { id: 50, suit_id: 5, environment_colour_id: 5 },
    { id: 51, suit_id: 3, environment_colour_id: 1 },
    { id: 52, suit_id: 4, environment_colour_id: 2 },
    { id: 53, suit_id: 1, environment_colour_id: 3 },
    { id: 54, suit_id: 2, environment_colour_id: 4 },
    { id: 55, suit_id: 5, environment_colour_id: 5 },
    { id: 56, suit_id: 4, environment_colour_id: 1 },
    { id: 57, suit_id: 1, environment_colour_id: 2 },
    { id: 58, suit_id: 2, environment_colour_id: 3 },
    { id: 59, suit_id: 3, environment_colour_id: 4 },
    { id: 60, suit_id: 5, environment_colour_id: 5 },
    { id: 61, suit_id: 1, environment_colour_id: 1 },
    { id: 62, suit_id: 2, environment_colour_id: 2 },
    { id: 63, suit_id: 3, environment_colour_id: 2 },
    { id: 64, suit_id: 4, environment_colour_id: 4 },
    { id: 65, suit_id: 5, environment_colour_id: 5 },
    { id: 66, suit_id: 2, environment_colour_id: 1 },
    { id: 67, suit_id: 3, environment_colour_id: 2 },
    { id: 68, suit_id: 4, environment_colour_id: 3 },
    { id: 69, suit_id: 1, environment_colour_id: 4 },
    { id: 70, suit_id: 5, environment_colour_id: 5 },
    { id: 71, suit_id: 3, environment_colour_id: 1 },
    { id: 72, suit_id: 4, environment_colour_id: 2 },
    { id: 73, suit_id: 1, environment_colour_id: 3 },
    { id: 74, suit_id: 2, environment_colour_id: 4 },
    { id: 75, suit_id: 5, environment_colour_id: 5 },
    { id: 76, suit_id: 4, environment_colour_id: 2 },
    { id: 77, suit_id: 1, environment_colour_id: 3 },
    { id: 78, suit_id: 2, environment_colour_id: 4 },
    { id: 79, suit_id: 3, environment_colour_id: 5 },
    { id: 80, suit_id: 5, environment_colour_id: 1 },
    { id: 81, suit_id: 1, environment_colour_id: 2 },
    { id: 82, suit_id: 2, environment_colour_id: 3 },
    { id: 83, suit_id: 3, environment_colour_id: 4 },
    { id: 84, suit_id: 4, environment_colour_id: 5 },
    { id: 85, suit_id: 5, environment_colour_id: 1 },
    { id: 86, suit_id: 2, environment_colour_id: 2 },
    { id: 87, suit_id: 3, environment_colour_id: 3 },
    { id: 88, suit_id: 4, environment_colour_id: 4 },
    { id: 89, suit_id: 1, environment_colour_id: 5 },
    { id: 90, suit_id: 5, environment_colour_id: 1 },
    { id: 91, suit_id: 3, environment_colour_id: 2 },
    { id: 92, suit_id: 4, environment_colour_id: 3 },
    { id: 93, suit_id: 1, environment_colour_id: 4 },
    { id: 94, suit_id: 2, environment_colour_id: 5 },
    { id: 95, suit_id: 5, environment_colour_id: 1 },
    { id: 96, suit_id: 4, environment_colour_id: 2 },
    { id: 97, suit_id: 1, environment_colour_id: 3 },
    { id: 98, suit_id: 2, environment_colour_id: 4 },
    { id: 99, suit_id: 3, environment_colour_id: 5 },
    { id: 100, suit_id: 5, environment_colour_id: 1 },
  ])
*/