export async function seed(knex) {
  await knex('boardgames').del()
  await knex('boardgames').insert([
    {
      id: 1,
      name: '5-Minute Dungeon',
      player_count: '2-5',
      play_time: '5-30',
      category: '',
      personal_rating: '',
      bgg_rating: '6.9',
      status: 'owned (for trade)',
      bgg_objectid: '207830',
    },
    {
      id: 2,
      name: '6 nimmt! 25 Jahre',
      player_count: '2-10',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '7.25',
      status: 'owned',
      bgg_objectid: '268586',
    },
    {
      id: 3,
      name: '7 Wonders Duel',
      player_count: '2',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '8.07',
      status: 'owned',
      bgg_objectid: '173346',
    },
    {
      id: 4,
      name: 'Adventure Land',
      player_count: '2-4',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '6.89',
      status: 'owned (for trade)',
      bgg_objectid: '183231',
    },
    {
      id: 5,
      name: 'The Adventures of Robin Hood',
      player_count: '2-4',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.41',
      status: 'owned',
      bgg_objectid: '326494',
    },
    {
      id: 6,
      name: 'Alhambra',
      player_count: '2-6',
      play_time: '45-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.04',
      status: 'owned',
      bgg_objectid: '6249',
    },
    {
      id: 7,
      name: "Ankh'or",
      player_count: '2-4',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '6.86',
      status: 'owned (for trade)',
      bgg_objectid: '271530',
    },
    {
      id: 8,
      name: 'Arboretum',
      player_count: '2-4',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.24',
      status: 'owned',
      bgg_objectid: '140934',
    },
    {
      id: 9,
      name: 'Articulate!',
      player_count: '4-8',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '6.53',
      status: 'owned',
      bgg_objectid: '6541',
    },
    {
      id: 10,
      name: 'Back to the Future: Back in Time',
      player_count: '2-4',
      play_time: '50',
      category: '',
      personal_rating: '',
      bgg_rating: '7.16',
      status: 'owned',
      bgg_objectid: '302388',
    },
    {
      id: 11,
      name: 'Back to the Future: Dice Through Time',
      player_count: '2-4',
      play_time: '45-60',
      category: '',
      personal_rating: '',
      bgg_rating: '6.64',
      status: 'owned',
      bgg_objectid: '292564',
    },
    {
      id: 12,
      name: 'Balderdash',
      player_count: '2-6',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '6.48',
      status: 'owned',
      bgg_objectid: '163',
    },
    {
      id: 13,
      name: 'Bananagrams',
      player_count: '1-8',
      play_time: '15',
      category: '',
      personal_rating: '',
      bgg_rating: '6.43',
      status: 'owned',
      bgg_objectid: '27225',
    },
    {
      id: 14,
      name: 'Bark Avenue',
      player_count: '1-5',
      play_time: '45-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.05',
      status: 'owned',
      bgg_objectid: '343684',
    },
    {
      id: 15,
      name: 'Battleship: Card Game',
      player_count: '2',
      play_time: '15',
      category: '',
      personal_rating: '5.5',
      bgg_rating: '5.89',
      status: 'owned',
      bgg_objectid: '120580',
    },
    {
      id: 16,
      name: 'Bears vs Babies',
      player_count: '2-5',
      play_time: '15-20',
      category: '',
      personal_rating: '6',
      bgg_rating: '5.37',
      status: 'owned',
      bgg_objectid: '211534',
    },
    {
      id: 17,
      name: 'Betrayal at House on the Hill',
      player_count: '3-6',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.01',
      status: 'owned',
      bgg_objectid: '10547',
    },
    {
      id: 18,
      name: 'Beyond Baker Street',
      player_count: '2-4',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '6.8',
      status: 'owned',
      bgg_objectid: '168681',
    },
    {
      id: 19,
      name: 'BONK',
      player_count: '2-4',
      play_time: '10',
      category: '',
      personal_rating: '6.5',
      bgg_rating: '6.61',
      status: 'owned (for trade)',
      bgg_objectid: '230852',
    },
    {
      id: 20,
      name: 'Books of Time',
      player_count: '1-4',
      play_time: '45-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.06',
      status: 'owned',
      bgg_objectid: '372631',
    },
    {
      id: 21,
      name: 'Brass: Lancashire',
      player_count: '2-4',
      play_time: '60-120',
      category: '',
      personal_rating: '',
      bgg_rating: '8.2',
      status: 'owned',
      bgg_objectid: '28720',
    },
    {
      id: 22,
      name: 'Break the Safe',
      player_count: '2-4',
      play_time: '30',
      category: '',
      personal_rating: '7',
      bgg_rating: '6.08',
      status: 'owned',
      bgg_objectid: '7824',
    },
    {
      id: 23,
      name: 'Café',
      player_count: '1-4',
      play_time: '20-45',
      category: '',
      personal_rating: '7',
      bgg_rating: '7.14',
      status: 'owned',
      bgg_objectid: '284936',
    },
    {
      id: 24,
      name: 'Calico',
      player_count: '1-4',
      play_time: '30-45',
      category: '',
      personal_rating: '',
      bgg_rating: '7.47',
      status: 'owned',
      bgg_objectid: '283155',
    },
    {
      id: 25,
      name: 'Carcassonne: Hunters and Gatherers',
      player_count: '2-5',
      play_time: '35-40',
      category: '',
      personal_rating: '9',
      bgg_rating: '7.13',
      status: 'owned',
      bgg_objectid: '4390',
    },
    {
      id: 26,
      name: 'Carcassonne: King & Scout',
      player_count: '2-5',
      play_time: '45',
      category: '',
      personal_rating: '5',
      bgg_rating: '6.6',
      status: 'owned',
      bgg_objectid: '7707',
    },
    {
      id: 27,
      name: 'Carcassonne: South Seas',
      player_count: '2-5',
      play_time: '35',
      category: '',
      personal_rating: '',
      bgg_rating: '7.05',
      status: 'owned',
      bgg_objectid: '147303',
    },
    {
      id: 28,
      name: 'Carcassonne: The Discovery',
      player_count: '2-5',
      play_time: '30-45',
      category: '',
      personal_rating: '7',
      bgg_rating: '6.48',
      status: 'owned',
      bgg_objectid: '16216',
    },
    {
      id: 29,
      name: 'Cards Against Humanity: Family Edition',
      player_count: '4-30',
      play_time: '30',
      category: '',
      personal_rating: '6.5',
      bgg_rating: '6.1',
      status: 'owned',
      bgg_objectid: '317367',
    },
    {
      id: 30,
      name: 'The Castles of Burgundy',
      player_count: '2-4',
      play_time: '30-90',
      category: '',
      personal_rating: '',
      bgg_rating: '8.16',
      status: 'owned',
      bgg_objectid: '84876',
    },
    {
      id: 31,
      name: 'Catan',
      player_count: '3-4',
      play_time: '60-120',
      category: '',
      personal_rating: '7',
      bgg_rating: '7.09',
      status: 'owned',
      bgg_objectid: '13',
    },
    {
      id: 32,
      name: 'Catan: Cities & Knights',
      player_count: '3-4',
      play_time: '90-150',
      category: '',
      personal_rating: '',
      bgg_rating: '7.45',
      status: 'owned',
      bgg_objectid: '926',
    },
    {
      id: 33,
      name: 'Catan: Seafarers',
      player_count: '3-4',
      play_time: '90',
      category: '',
      personal_rating: '',
      bgg_rating: '7.17',
      status: 'owned',
      bgg_objectid: '325',
    },
    {
      id: 34,
      name: 'Century: Golem Edition',
      player_count: '2-5',
      play_time: '30-45',
      category: '',
      personal_rating: '8',
      bgg_rating: '7.57',
      status: 'owned',
      bgg_objectid: '232832',
    },
    {
      id: 35,
      name: 'Chess',
      player_count: '2',
      play_time: '0',
      category: '',
      personal_rating: '8',
      bgg_rating: '7.24',
      status: 'owned',
      bgg_objectid: '171',
    },
    {
      id: 36,
      name: 'Chronicles of Crime',
      player_count: '1-4',
      play_time: '60-90',
      category: '',
      personal_rating: '',
      bgg_rating: '7.52',
      status: 'owned',
      bgg_objectid: '239188',
    },
    {
      id: 37,
      name: 'Chronicles of Crime: 1400',
      player_count: '1-4',
      play_time: '60-90',
      category: '',
      personal_rating: '',
      bgg_rating: '7.68',
      status: 'owned',
      bgg_objectid: '300300',
    },
    {
      id: 38,
      name: 'Chronicles of Crime: 1900',
      player_count: '1-4',
      play_time: '60-90',
      category: '',
      personal_rating: '8',
      bgg_rating: '7.88',
      status: 'owned',
      bgg_objectid: '302098',
    },
    {
      id: 39,
      name: 'Chronicles of Crime: 2400',
      player_count: '1-4',
      play_time: '60-90',
      category: '',
      personal_rating: '',
      bgg_rating: '7.6',
      status: 'owned',
      bgg_objectid: '302312',
    },
    {
      id: 40,
      name: 'Chronicles of Crime: Noir',
      player_count: '1-4',
      play_time: '60-90',
      category: '',
      personal_rating: '',
      bgg_rating: '7.96',
      status: 'owned',
      bgg_objectid: '249811',
    },
    {
      id: 41,
      name: 'Chronicles of Crime: The Millennium Series – Chronicles of Time Expansion',
      player_count: '1-4',
      play_time: '60-90',
      category: '',
      personal_rating: '',
      bgg_rating: '7.86',
      status: 'owned',
      bgg_objectid: '313301',
    },
    {
      id: 42,
      name: 'Chronicles of Crime: Welcome to Redview',
      player_count: '1-4',
      play_time: '30-90',
      category: '',
      personal_rating: '',
      bgg_rating: '7.62',
      status: 'owned',
      bgg_objectid: '258089',
    },
    {
      id: 43,
      name: 'Cinco Linko',
      player_count: '2-4',
      play_time: '5-15',
      category: '',
      personal_rating: '',
      bgg_rating: '6.59',
      status: 'owned',
      bgg_objectid: '208808',
    },
    {
      id: 44,
      name: 'Circadians: First Light',
      player_count: '1-4',
      play_time: '60-90',
      category: '',
      personal_rating: '',
      bgg_rating: '7.51',
      status: 'owned',
      bgg_objectid: '264052',
    },
    {
      id: 45,
      name: 'Citadels',
      player_count: '2-8',
      play_time: '30-60',
      category: '',
      personal_rating: '7',
      bgg_rating: '7.23',
      status: 'owned',
      bgg_objectid: '205398',
    },
    {
      id: 46,
      name: 'Clacks: A Discworld Board Game',
      player_count: '1-4',
      play_time: '45-30',
      category: '',
      personal_rating: '',
      bgg_rating: '6.21',
      status: 'owned',
      bgg_objectid: '140279',
    },
    {
      id: 47,
      name: 'Clank! Expeditions: Gold and Silk',
      player_count: '2-4',
      play_time: '30-60',
      category: '',
      personal_rating: '',
      bgg_rating: '8',
      status: 'owned',
      bgg_objectid: '257276',
    },
    {
      id: 48,
      name: 'Clank!: A Deck-Building Adventure',
      player_count: '2-4',
      play_time: '30-60',
      category: '',
      personal_rating: '7',
      bgg_rating: '7.76',
      status: 'owned',
      bgg_objectid: '201808',
    },
    {
      id: 49,
      name: 'Clash of Decks: Starter Kit',
      player_count: '1-2',
      play_time: '15-30',
      category: '',
      personal_rating: '',
      bgg_rating: '6.28',
      status: 'owned',
      bgg_objectid: '334307',
    },
    {
      id: 50,
      name: 'Clue',
      player_count: '2-6',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '5.69',
      status: 'owned',
      bgg_objectid: '1294',
    },
    {
      id: 51,
      name: 'Clue: Treachery at Tudor Mansion',
      player_count: '1-6',
      play_time: '90',
      category: '',
      personal_rating: '',
      bgg_rating: '6.31',
      status: 'owned',
      bgg_objectid: '369483',
    },
    {
      id: 52,
      name: 'Cobras',
      player_count: '1-5',
      play_time: '30-45',
      category: '',
      personal_rating: '',
      bgg_rating: '6.8',
      status: 'owned',
      bgg_objectid: '199047',
    },
    {
      id: 53,
      name: 'Coloretto',
      player_count: '2-5',
      play_time: '30',
      category: '',
      personal_rating: '7.5',
      bgg_rating: '6.98',
      status: 'owned',
      bgg_objectid: '5782',
    },
    {
      id: 54,
      name: 'Colt Express',
      player_count: '2-6',
      play_time: '40',
      category: '',
      personal_rating: '',
      bgg_rating: '7.1',
      status: 'owned',
      bgg_objectid: '158899',
    },
    {
      id: 55,
      name: 'Confident?',
      player_count: '3-99',
      play_time: '20-40',
      category: '',
      personal_rating: '7',
      bgg_rating: '6.61',
      status: 'owned',
      bgg_objectid: '251726',
    },
    {
      id: 56,
      name: 'Coup',
      player_count: '2-6',
      play_time: '15',
      category: '',
      personal_rating: '',
      bgg_rating: '6.98',
      status: 'owned',
      bgg_objectid: '131357',
    },
    {
      id: 57,
      name: 'The Crew: The Quest for Planet Nine',
      player_count: '2-5',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.75',
      status: 'owned',
      bgg_objectid: '284083',
    },
    {
      id: 58,
      name: 'Crimopolis',
      player_count: '2-5',
      play_time: '30-100',
      category: '',
      personal_rating: '',
      bgg_rating: '7.12',
      status: 'owned (for trade)',
      bgg_objectid: '260904',
    },
    {
      id: 59,
      name: 'Crown of Emara',
      player_count: '1-4',
      play_time: '45-75',
      category: '',
      personal_rating: '',
      bgg_rating: '7.34',
      status: 'owned',
      bgg_objectid: '256570',
    },
    {
      id: 60,
      name: 'Decrypto',
      player_count: '3-8',
      play_time: '15-45',
      category: '',
      personal_rating: '7',
      bgg_rating: '7.76',
      status: 'owned',
      bgg_objectid: '225694',
    },
    {
      id: 61,
      name: 'Detective: A Modern Crime Board Game',
      player_count: '1-5',
      play_time: '120-180',
      category: '',
      personal_rating: '',
      bgg_rating: '7.6',
      status: 'owned',
      bgg_objectid: '223321',
    },
    {
      id: 62,
      name: 'Discworld: Ankh-Morpork',
      player_count: '2-4',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.26',
      status: 'owned',
      bgg_objectid: '91312',
    },
    {
      id: 63,
      name: 'Dominion: Prosperity',
      player_count: '2-4',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '8.22',
      status: 'owned',
      bgg_objectid: '66690',
    },
    {
      id: 64,
      name: 'Dominion: Second Edition',
      player_count: '2-4',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.82',
      status: 'owned',
      bgg_objectid: '209418',
    },
    {
      id: 65,
      name: "Don't Get Got!",
      player_count: '2-10',
      play_time: '0',
      category: '',
      personal_rating: '',
      bgg_rating: '6.92',
      status: 'owned (for trade)',
      bgg_objectid: '262547',
    },
    {
      id: 66,
      name: 'Downspin',
      player_count: '2',
      play_time: '30',
      category: '',
      personal_rating: '6.5',
      bgg_rating: '5.52',
      status: 'owned',
      bgg_objectid: '1099',
    },
    {
      id: 67,
      name: 'Dungeons & Dragons Starter Set',
      player_count: '2-6',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.69',
      status: 'owned',
      bgg_objectid: '94902',
    },
    {
      id: 68,
      name: 'E.T. The Extra-Terrestrial: Light Years From Home Game',
      player_count: '2-4',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '6.79',
      status: 'owned (for trade)',
      bgg_objectid: '355772',
    },
    {
      id: 69,
      name: 'Escape Tales: Low Memory',
      player_count: '1-4',
      play_time: '360-540',
      category: '',
      personal_rating: '',
      bgg_rating: '6.6',
      status: 'owned',
      bgg_objectid: '282291',
    },
    {
      id: 70,
      name: 'Evolution',
      player_count: '2-6',
      play_time: '60',
      category: '',
      personal_rating: '7',
      bgg_rating: '7',
      status: 'owned',
      bgg_objectid: '155703',
    },
    {
      id: 71,
      name: 'Exploding Kittens',
      player_count: '2-5',
      play_time: '15',
      category: '',
      personal_rating: '6.5',
      bgg_rating: '6.07',
      status: 'owned',
      bgg_objectid: '172225',
    },
    {
      id: 72,
      name: 'Fleet',
      player_count: '2-4',
      play_time: '30-45',
      category: '',
      personal_rating: '',
      bgg_rating: '6.81',
      status: 'owned',
      bgg_objectid: '121297',
    },
    {
      id: 73,
      name: 'Fleet: The Dice Game (Second Edition)',
      player_count: '1-4',
      play_time: '30-45',
      category: '',
      personal_rating: '',
      bgg_rating: '7.73',
      status: 'owned',
      bgg_objectid: '328326',
    },
    {
      id: 74,
      name: 'Flip 7',
      player_count: '3-18',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.21',
      status: 'owned',
      bgg_objectid: '420087',
    },
    {
      id: 75,
      name: 'Foosketball',
      player_count: '1-2',
      play_time: '5-15',
      category: '',
      personal_rating: '',
      bgg_rating: '6.12',
      status: 'owned',
      bgg_objectid: '333672',
    },
    {
      id: 76,
      name: 'For Sale',
      player_count: '3-6',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.27',
      status: 'owned',
      bgg_objectid: '172',
    },
    {
      id: 77,
      name: 'Fort',
      player_count: '2-4',
      play_time: '20-40',
      category: '',
      personal_rating: '',
      bgg_rating: '7.05',
      status: 'owned',
      bgg_objectid: '296912',
    },
    {
      id: 78,
      name: 'The Fox in the Forest',
      player_count: '2',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.05',
      status: 'owned',
      bgg_objectid: '221965',
    },
    {
      id: 79,
      name: 'Funkoverse Strategy Game: Jurassic Park 100',
      player_count: '2-4',
      play_time: '20-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.06',
      status: 'owned (for trade)',
      bgg_objectid: '299266',
    },
    {
      id: 80,
      name: "Funkoverse Strategy Game: Tim Burton's The Nightmare Before Christmas 101",
      player_count: '2-4',
      play_time: '20-60',
      category: '',
      personal_rating: '',
      bgg_rating: '6.96',
      status: 'owned (for trade)',
      bgg_objectid: '394337',
    },
    {
      id: 81,
      name: 'The Game: Face to Face',
      player_count: '2',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.04',
      status: 'owned',
      bgg_objectid: '236461',
    },
    {
      id: 82,
      name: 'Gloom',
      player_count: '2-5',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '6.33',
      status: 'owned',
      bgg_objectid: '12692',
    },
    {
      id: 83,
      name: 'Granny Wars:  A Game of Tit for Tat',
      player_count: '2-8',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '6.16',
      status: 'owned (for trade)',
      bgg_objectid: '146765',
    },
    {
      id: 84,
      name: 'Great Western Trail: New Zealand',
      player_count: '1-4',
      play_time: '75-150',
      category: '',
      personal_rating: '',
      bgg_rating: '8.45',
      status: 'owned',
      bgg_objectid: '380607',
    },
    {
      id: 85,
      name: 'Groundhog Day: The Game',
      player_count: '2-6',
      play_time: '15-25',
      category: '',
      personal_rating: '',
      bgg_rating: '7.18',
      status: 'owned',
      bgg_objectid: '318359',
    },
    {
      id: 86,
      name: 'Guess Who?',
      player_count: '2',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '4.86',
      status: 'owned',
      bgg_objectid: '4143',
    },
    {
      id: 87,
      name: 'Guess Who?: Card Game',
      player_count: '2',
      play_time: '0',
      category: '',
      personal_rating: '',
      bgg_rating: '4.76',
      status: 'owned',
      bgg_objectid: '302584',
    },
    {
      id: 88,
      name: 'Hanabi',
      player_count: '2-5',
      play_time: '25',
      category: '',
      personal_rating: '',
      bgg_rating: '7.03',
      status: 'owned',
      bgg_objectid: '98778',
    },
    {
      id: 89,
      name: 'Heat: Pedal to the Metal',
      player_count: '1-6',
      play_time: '30-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.99',
      status: 'owned',
      bgg_objectid: '366013',
    },
    {
      id: 90,
      name: 'Hive',
      player_count: '2',
      play_time: '20',
      category: '',
      personal_rating: '8',
      bgg_rating: '7.31',
      status: 'owned',
      bgg_objectid: '2655',
    },
    {
      id: 91,
      name: 'Hive: The Ladybug',
      player_count: '2',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.6',
      status: 'owned',
      bgg_objectid: '70704',
    },
    {
      id: 92,
      name: 'Hive: The Mosquito',
      player_count: '2',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.56',
      status: 'owned',
      bgg_objectid: '30323',
    },
    {
      id: 93,
      name: 'Hive: The Pillbug',
      player_count: '2',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.72',
      status: 'owned',
      bgg_objectid: '139666',
    },
    {
      id: 94,
      name: 'The Hobbit: There and Back Again',
      player_count: '1-4',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.58',
      status: 'owned',
      bgg_objectid: '436215',
    },
    {
      id: 95,
      name: 'The Hunger',
      player_count: '2-6',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '6.99',
      status: 'owned',
      bgg_objectid: '339906',
    },
    {
      id: 96,
      name: 'Infinity Gauntlet: A Love Letter Game',
      player_count: '2-6',
      play_time: '15',
      category: '',
      personal_rating: '',
      bgg_rating: '6.91',
      status: 'owned',
      bgg_objectid: '304285',
    },
    {
      id: 97,
      name: "It's a Wonderful Kingdom",
      player_count: '1-2',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '7.05',
      status: 'owned',
      bgg_objectid: '327711',
    },
    {
      id: 98,
      name: 'IUNU',
      player_count: '2-4',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '6.62',
      status: 'owned',
      bgg_objectid: '148507',
    },
    {
      id: 99,
      name: 'Jaipur',
      player_count: '2',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.48',
      status: 'owned',
      bgg_objectid: '54043',
    },
    {
      id: 100,
      name: "Jane Austen's Matchmaker",
      player_count: '3-6',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '6.3',
      status: 'owned',
      bgg_objectid: '151645',
    },
    {
      id: 101,
      name: 'Jungle Speed',
      player_count: '2-10',
      play_time: '10',
      category: '',
      personal_rating: '',
      bgg_rating: '6.45',
      status: 'owned',
      bgg_objectid: '8098',
    },
    {
      id: 102,
      name: 'Kalah',
      player_count: '2',
      play_time: '10',
      category: '',
      personal_rating: '',
      bgg_rating: '6.02',
      status: 'owned',
      bgg_objectid: '2448',
    },
    {
      id: 103,
      name: 'Khôra: Rise of an Empire',
      player_count: '2-4',
      play_time: '75',
      category: '',
      personal_rating: '',
      bgg_rating: '7.35',
      status: 'owned',
      bgg_objectid: '299684',
    },
    {
      id: 104,
      name: 'Kids Chronicles: Quest for the Moon Stones',
      player_count: '1-4',
      play_time: '30-45',
      category: '',
      personal_rating: '',
      bgg_rating: '7.22',
      status: 'owned',
      bgg_objectid: '340288',
    },
    {
      id: 105,
      name: 'Kill The Unicorns',
      player_count: '3-6',
      play_time: '25-45',
      category: '',
      personal_rating: '',
      bgg_rating: '6.81',
      status: 'owned',
      bgg_objectid: '204602',
    },
    {
      id: 106,
      name: 'King of Tokyo: Dark Edition',
      player_count: '2-6',
      play_time: '30',
      category: '',
      personal_rating: '7.5',
      bgg_rating: '7.64',
      status: 'owned',
      bgg_objectid: '293141',
    },
    {
      id: 107,
      name: 'Kingdomino',
      player_count: '2-4',
      play_time: '15-25',
      category: '',
      personal_rating: '',
      bgg_rating: '7.29',
      status: 'owned',
      bgg_objectid: '204583',
    },
    {
      id: 108,
      name: 'Kingdomino Origins',
      player_count: '2-4',
      play_time: '20-40',
      category: '',
      personal_rating: '',
      bgg_rating: '7.44',
      status: 'owned',
      bgg_objectid: '340041',
    },
    {
      id: 109,
      name: 'KLASK',
      player_count: '2',
      play_time: '10',
      category: '',
      personal_rating: '',
      bgg_rating: '7.62',
      status: 'owned',
      bgg_objectid: '165722',
    },
    {
      id: 110,
      name: 'Legacy of Yu',
      player_count: '1',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '8.07',
      status: 'owned',
      bgg_objectid: '354934',
    },
    {
      id: 111,
      name: 'Llamas Unleashed',
      player_count: '2-8',
      play_time: '30-45',
      category: '',
      personal_rating: '',
      bgg_rating: '6.09',
      status: 'owned',
      bgg_objectid: '268936',
    },
    {
      id: 112,
      name: 'Loot',
      player_count: '2-8',
      play_time: '20',
      category: '',
      personal_rating: '6',
      bgg_rating: '6.3',
      status: 'owned',
      bgg_objectid: '770',
    },
    {
      id: 113,
      name: 'The Lord of the Rings: Fate of the Fellowship',
      player_count: '1-5',
      play_time: '60-150',
      category: '',
      personal_rating: '',
      bgg_rating: '8.34',
      status: 'owned',
      bgg_objectid: '436217',
    },
    {
      id: 114,
      name: 'The Lord of the Rings: The Two Towers – Trick-Taking Game',
      player_count: '1-4',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '8.38',
      status: 'owned',
      bgg_objectid: '448271',
    },
    {
      id: 115,
      name: 'Lost Cities',
      player_count: '2',
      play_time: '30',
      category: '',
      personal_rating: '8',
      bgg_rating: '7.26',
      status: 'owned',
      bgg_objectid: '50',
    },
    {
      id: 116,
      name: 'Lost Cities: Rivals',
      player_count: '2-4',
      play_time: '40',
      category: '',
      personal_rating: '',
      bgg_rating: '6.65',
      status: 'owned (for trade)',
      bgg_objectid: '253398',
    },
    {
      id: 117,
      name: 'Lost Ruins of Arnak',
      player_count: '1-4',
      play_time: '30-120',
      category: '',
      personal_rating: '8',
      bgg_rating: '8.08',
      status: 'owned',
      bgg_objectid: '312484',
    },
    {
      id: 118,
      name: 'Lost Ruins of Arnak: Expedition Leaders',
      player_count: '1-4',
      play_time: '30-120',
      category: '',
      personal_rating: '7.5',
      bgg_rating: '8.71',
      status: 'owned',
      bgg_objectid: '341254',
    },
    {
      id: 119,
      name: 'Love Letter',
      player_count: '2-4',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.23',
      status: 'owned',
      bgg_objectid: '129622',
    },
    {
      id: 120,
      name: 'Love Letter',
      player_count: '2-6',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.5',
      status: 'owned',
      bgg_objectid: '277085',
    },
    {
      id: 121,
      name: 'Love Letter: Adventure Time',
      player_count: '2-4',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.27',
      status: 'owned',
      bgg_objectid: '175307',
    },
    {
      id: 122,
      name: 'Magic: The Gathering – Zendikar Rising',
      player_count: '2-8',
      play_time: '0',
      category: '',
      personal_rating: '',
      bgg_rating: '7.34',
      status: 'owned',
      bgg_objectid: '360198',
    },
    {
      id: 123,
      name: 'Mariposas',
      player_count: '2-5',
      play_time: '45-75',
      category: '',
      personal_rating: '',
      bgg_rating: '6.73',
      status: 'owned',
      bgg_objectid: '297978',
    },
    {
      id: 124,
      name: 'Medium',
      player_count: '2-8',
      play_time: '30-45',
      category: '',
      personal_rating: '',
      bgg_rating: '6.82',
      status: 'owned',
      bgg_objectid: '242529',
    },
    {
      id: 125,
      name: 'Mhing',
      player_count: '2-6',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '6.71',
      status: 'owned',
      bgg_objectid: '1452',
    },
    {
      id: 126,
      name: 'The Mind',
      player_count: '2-4',
      play_time: '20',
      category: '',
      personal_rating: '7',
      bgg_rating: '6.71',
      status: 'owned',
      bgg_objectid: '244992',
    },
    {
      id: 127,
      name: 'Most Wanted',
      player_count: '2-8',
      play_time: '15-35',
      category: '',
      personal_rating: '',
      bgg_rating: '6.5',
      status: 'owned',
      bgg_objectid: '246146',
    },
    {
      id: 128,
      name: 'Mountain of Inferno',
      player_count: '2-4',
      play_time: '25',
      category: '',
      personal_rating: '',
      bgg_rating: '5.63',
      status: 'owned (for trade)',
      bgg_objectid: '39802',
    },
    {
      id: 129,
      name: 'Muffin Time',
      player_count: '2-8',
      play_time: '20-40',
      category: '',
      personal_rating: '',
      bgg_rating: '6.2',
      status: 'owned',
      bgg_objectid: '286735',
    },
    {
      id: 130,
      name: 'Murder Mystery Party: A Taste for Wine and Murder',
      player_count: '6-8',
      play_time: '180',
      category: '',
      personal_rating: '',
      bgg_rating: '6.52',
      status: 'owned',
      bgg_objectid: '6448',
    },
    {
      id: 131,
      name: 'Murder Mystery Party: Pasta, Passion & Pistols',
      player_count: '6-8',
      play_time: '180',
      category: '',
      personal_rating: '',
      bgg_rating: '5.9',
      status: 'owned',
      bgg_objectid: '6449',
    },
    {
      id: 132,
      name: 'Neuroshima Hex',
      player_count: '2-4',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.38',
      status: 'owned (for trade)',
      bgg_objectid: '21241',
    },
    {
      id: 133,
      name: 'New World: A Carcassonne Game',
      player_count: '2-5',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '6.48',
      status: 'owned',
      bgg_objectid: '34615',
    },
    {
      id: 134,
      name: 'Nidavellir',
      player_count: '2-5',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '7.55',
      status: 'owned',
      bgg_objectid: '293014',
    },
    {
      id: 135,
      name: 'Nidavellir: Thingvellir',
      player_count: '2-5',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '7.71',
      status: 'owned',
      bgg_objectid: '326984',
    },
    {
      id: 136,
      name: 'Nightmare',
      player_count: '3-6',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '5.96',
      status: 'owned',
      bgg_objectid: '5641',
    },
    {
      id: 137,
      name: 'No Thanks!',
      player_count: '3-7',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.08',
      status: 'owned',
      bgg_objectid: '12942',
    },
    {
      id: 138,
      name: 'Oath',
      player_count: '1-6',
      play_time: '45-150',
      category: '',
      personal_rating: '',
      bgg_rating: '7.71',
      status: 'owned',
      bgg_objectid: '291572',
    },
    {
      id: 139,
      name: 'One Night Ultimate Alien',
      player_count: '4-10',
      play_time: '10',
      category: '',
      personal_rating: '',
      bgg_rating: '6.89',
      status: 'owned',
      bgg_objectid: '204431',
    },
    {
      id: 140,
      name: 'One Night Ultimate Vampire',
      player_count: '3-10',
      play_time: '10',
      category: '',
      personal_rating: '',
      bgg_rating: '6.65',
      status: 'owned',
      bgg_objectid: '180956',
    },
    {
      id: 141,
      name: 'One Night Ultimate Werewolf',
      player_count: '3-10',
      play_time: '10',
      category: '',
      personal_rating: '8.5',
      bgg_rating: '7.03',
      status: 'owned',
      bgg_objectid: '147949',
    },
    {
      id: 142,
      name: 'Othello',
      player_count: '2',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '6.16',
      status: 'owned',
      bgg_objectid: '2389',
    },
    {
      id: 143,
      name: 'Otys',
      player_count: '1-4',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '6.94',
      status: 'owned',
      bgg_objectid: '222542',
    },
    {
      id: 144,
      name: 'Paladins of the West Kingdom',
      player_count: '1-4',
      play_time: '90-120',
      category: '',
      personal_rating: '',
      bgg_rating: '7.95',
      status: 'owned',
      bgg_objectid: '266810',
    },
    {
      id: 145,
      name: 'Paleo',
      player_count: '2-4',
      play_time: '45-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.64',
      status: 'owned',
      bgg_objectid: '300531',
    },
    {
      id: 146,
      name: 'Parade',
      player_count: '2-6',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '7',
      status: 'owned',
      bgg_objectid: '56692',
    },
    {
      id: 147,
      name: 'Parks',
      player_count: '1-5',
      play_time: '30-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.61',
      status: 'owned (for trade)',
      bgg_objectid: '266524',
    },
    {
      id: 148,
      name: 'Parks: Nightfall',
      player_count: '1-5',
      play_time: '40-70',
      category: '',
      personal_rating: '',
      bgg_rating: '8.14',
      status: 'owned (for trade)',
      bgg_objectid: '298729',
    },
    {
      id: 149,
      name: 'Patchwork',
      player_count: '2',
      play_time: '15-30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.58',
      status: 'owned',
      bgg_objectid: '163412',
    },
    {
      id: 150,
      name: 'Pendulum',
      player_count: '1-5',
      play_time: '60-90',
      category: '',
      personal_rating: '',
      bgg_rating: '6.38',
      status: 'owned',
      bgg_objectid: '312804',
    },
    {
      id: 151,
      name: 'Phase 10',
      player_count: '2-6',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '5.29',
      status: 'owned',
      bgg_objectid: '1258',
    },
    {
      id: 152,
      name: 'Pictionary',
      player_count: '3-16',
      play_time: '90',
      category: '',
      personal_rating: '',
      bgg_rating: '5.86',
      status: 'owned',
      bgg_objectid: '2281',
    },
    {
      id: 153,
      name: 'Pictureka!',
      player_count: '2-7',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '5.5',
      status: 'owned',
      bgg_objectid: '22889',
    },
    {
      id: 154,
      name: 'Pictures',
      player_count: '3-5',
      play_time: '20-30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.22',
      status: 'owned',
      bgg_objectid: '284108',
    },
    {
      id: 155,
      name: 'Point Salad',
      player_count: '2-6',
      play_time: '15-30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.08',
      status: 'owned (for trade)',
      bgg_objectid: '274960',
    },
    {
      id: 156,
      name: 'Police Precinct',
      player_count: '1-6',
      play_time: '90',
      category: '',
      personal_rating: '',
      bgg_rating: '6.84',
      status: 'owned',
      bgg_objectid: '118536',
    },
    {
      id: 157,
      name: 'Project L',
      player_count: '1-4',
      play_time: '20-40',
      category: '',
      personal_rating: '',
      bgg_rating: '7.44',
      status: 'owned',
      bgg_objectid: '260180',
    },
    {
      id: 158,
      name: 'Project L: Finesse',
      player_count: '1-4',
      play_time: '20-40',
      category: '',
      personal_rating: '',
      bgg_rating: '7.66',
      status: 'owned',
      bgg_objectid: '287508',
    },
    {
      id: 159,
      name: 'Project L: Ghost Piece',
      player_count: '1-6',
      play_time: '20-40',
      category: '',
      personal_rating: '',
      bgg_rating: '7.82',
      status: 'owned',
      bgg_objectid: '284988',
    },
    {
      id: 160,
      name: 'Puerto Rico',
      player_count: '2-5',
      play_time: '90-150',
      category: '',
      personal_rating: '',
      bgg_rating: '8.3',
      status: 'owned',
      bgg_objectid: '108687',
    },
    {
      id: 161,
      name: 'Puerto Rico 1897: Special Edition',
      player_count: '1-5',
      play_time: '60-120',
      category: '',
      personal_rating: '',
      bgg_rating: '8.66',
      status: 'owned',
      bgg_objectid: '415843',
    },
    {
      id: 162,
      name: 'Quacks',
      player_count: '2-4',
      play_time: '45',
      category: '',
      personal_rating: '8',
      bgg_rating: '7.8',
      status: 'owned',
      bgg_objectid: '244521',
    },
    {
      id: 163,
      name: 'The Quacks of Quedlinburg: The Herb Witches',
      player_count: '2-5',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '8',
      status: 'owned',
      bgg_objectid: '269259',
    },
    {
      id: 164,
      name: 'Qwirkle',
      player_count: '2-4',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '6.77',
      status: 'owned',
      bgg_objectid: '25669',
    },
    {
      id: 165,
      name: 'Race for the Galaxy',
      player_count: '2-4',
      play_time: '30-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.74',
      status: 'owned',
      bgg_objectid: '28143',
    },
    {
      id: 166,
      name: 'Raid the Pantry',
      player_count: '2-4',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.03',
      status: 'owned',
      bgg_objectid: '124918',
    },
    {
      id: 167,
      name: 'Raiders of Scythia',
      player_count: '1-4',
      play_time: '60-80',
      category: '',
      personal_rating: '',
      bgg_rating: '7.69',
      status: 'owned',
      bgg_objectid: '301880',
    },
    {
      id: 168,
      name: 'Raiders of the North Sea',
      player_count: '2-4',
      play_time: '60-80',
      category: '',
      personal_rating: '',
      bgg_rating: '7.72',
      status: 'owned',
      bgg_objectid: '170042',
    },
    {
      id: 169,
      name: 'Regicide',
      player_count: '1-4',
      play_time: '10-30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.39',
      status: 'owned',
      bgg_objectid: '307002',
    },
    {
      id: 170,
      name: 'Reign of Cthulhu',
      player_count: '2-4',
      play_time: '40',
      category: '',
      personal_rating: '',
      bgg_rating: '7.36',
      status: 'owned',
      bgg_objectid: '192153',
    },
    {
      id: 171,
      name: 'The Resistance',
      player_count: '5-10',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.19',
      status: 'owned',
      bgg_objectid: '41114',
    },
    {
      id: 172,
      name: 'Risk Legacy',
      player_count: '3-5',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.35',
      status: 'owned',
      bgg_objectid: '105134',
    },
    {
      id: 173,
      name: 'Rivals for Catan',
      player_count: '2',
      play_time: '45-60',
      category: '',
      personal_rating: '',
      bgg_rating: '6.93',
      status: 'owned (for trade)',
      bgg_objectid: '66056',
    },
    {
      id: 174,
      name: 'The Rocketeer: Fate of the Future',
      player_count: '2',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '7',
      status: 'owned',
      bgg_objectid: '344759',
    },
    {
      id: 175,
      name: 'Root',
      player_count: '2-4',
      play_time: '60-90',
      category: '',
      personal_rating: '',
      bgg_rating: '8.07',
      status: 'owned',
      bgg_objectid: '237182',
    },
    {
      id: 176,
      name: 'Root: Marauder Hirelings Pack & Hireling Box',
      player_count: '2-4',
      play_time: '60-90',
      category: '',
      personal_rating: '',
      bgg_rating: '8.46',
      status: 'owned',
      bgg_objectid: '336276',
    },
    {
      id: 177,
      name: 'Root: The Marauder Expansion',
      player_count: '2-6',
      play_time: '60-90',
      category: '',
      personal_rating: '',
      bgg_rating: '8.83',
      status: 'owned',
      bgg_objectid: '330149',
    },
    {
      id: 178,
      name: "Rubik's Race",
      player_count: '2',
      play_time: '5',
      category: '',
      personal_rating: '',
      bgg_rating: '6.06',
      status: 'owned',
      bgg_objectid: '614',
    },
    {
      id: 179,
      name: 'Rummikub',
      player_count: '2-4',
      play_time: '60',
      category: '',
      personal_rating: '',
      bgg_rating: '6.53',
      status: 'owned',
      bgg_objectid: '811',
    },
    {
      id: 180,
      name: 'Run, Fight, or Die!',
      player_count: '1-4',
      play_time: '40',
      category: '',
      personal_rating: '',
      bgg_rating: '6.82',
      status: 'owned',
      bgg_objectid: '89910',
    },
    {
      id: 181,
      name: 'San Juan',
      player_count: '2-4',
      play_time: '45-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.23',
      status: 'owned',
      bgg_objectid: '8217',
    },
    {
      id: 182,
      name: 'Santorini',
      player_count: '2-4',
      play_time: '20',
      category: '',
      personal_rating: '7.5',
      bgg_rating: '7.33',
      status: 'owned',
      bgg_objectid: '194655',
    },
    {
      id: 183,
      name: 'Scattergories',
      player_count: '2-6',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '6.31',
      status: 'owned',
      bgg_objectid: '2381',
    },
    {
      id: 184,
      name: 'Scotland Yard',
      player_count: '2-6',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '6.51',
      status: 'owned',
      bgg_objectid: '438',
    },
    {
      id: 185,
      name: 'Scrabble',
      player_count: '2-4',
      play_time: '90',
      category: '',
      personal_rating: '',
      bgg_rating: '6.28',
      status: 'owned',
      bgg_objectid: '320',
    },
    {
      id: 186,
      name: 'Scythe: The Rise of Fenris',
      player_count: '1-5',
      play_time: '75-150',
      category: '',
      personal_rating: '',
      bgg_rating: '8.69',
      status: 'owned',
      bgg_objectid: '242277',
    },
    {
      id: 187,
      name: 'The Search for Planet X',
      player_count: '1-4',
      play_time: '60-75',
      category: '',
      personal_rating: '',
      bgg_rating: '7.89',
      status: 'owned',
      bgg_objectid: '279537',
    },
    {
      id: 188,
      name: 'Sheriff of Nottingham: Merry Men',
      player_count: '3-6',
      play_time: '60-0',
      category: '',
      personal_rating: '',
      bgg_rating: '7.52',
      status: 'owned',
      bgg_objectid: '226065',
    },
    {
      id: 189,
      name: 'Sherlock Holmes Consulting Detective: The Baker Street Irregulars',
      player_count: '1-8',
      play_time: '90',
      category: '',
      personal_rating: '',
      bgg_rating: '8.17',
      status: 'owned',
      bgg_objectid: '296345',
    },
    {
      id: 190,
      name: 'Side Quest: Frostpunk',
      player_count: '1-4',
      play_time: '60-90',
      category: '',
      personal_rating: '',
      bgg_rating: '6.57',
      status: 'owned (for trade)',
      bgg_objectid: '420948',
    },
    {
      id: 191,
      name: 'Soda Smugglers',
      player_count: '3-8',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '6.7',
      status: 'owned',
      bgg_objectid: '338353',
    },
    {
      id: 192,
      name: 'Sparkle*Kitty',
      player_count: '3-8',
      play_time: '10-20',
      category: '',
      personal_rating: '',
      bgg_rating: '6.25',
      status: 'owned',
      bgg_objectid: '220547',
    },
    {
      id: 193,
      name: 'Spirit Island',
      player_count: '1-4',
      play_time: '90-120',
      category: '',
      personal_rating: '',
      bgg_rating: '8.34',
      status: 'owned',
      bgg_objectid: '162886',
    },
    {
      id: 194,
      name: 'Splendor',
      player_count: '2-4',
      play_time: '30',
      category: '',
      personal_rating: '9',
      bgg_rating: '7.42',
      status: 'owned',
      bgg_objectid: '148228',
    },
    {
      id: 195,
      name: 'Splendor Duel',
      player_count: '2',
      play_time: '30',
      category: '',
      personal_rating: '6',
      bgg_rating: '7.88',
      status: 'owned',
      bgg_objectid: '364073',
    },
    {
      id: 196,
      name: "Star Wars: Jabba's Palace – A Love Letter Game",
      player_count: '2-6',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.19',
      status: 'owned',
      bgg_objectid: '353470',
    },
    {
      id: 197,
      name: 'Struggle for Catan',
      player_count: '2-4',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '6.16',
      status: 'owned (for trade)',
      bgg_objectid: '91534',
    },
    {
      id: 198,
      name: 'Sunrise at the Studio',
      player_count: '1-4',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.27',
      status: 'owned',
      bgg_objectid: '389345',
    },
    {
      id: 199,
      name: 'Sushi Go Party!',
      player_count: '2-8',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.37',
      status: 'owned',
      bgg_objectid: '192291',
    },
    {
      id: 200,
      name: 'Sushi Go!',
      player_count: '2-5',
      play_time: '15',
      category: '',
      personal_rating: '',
      bgg_rating: '6.98',
      status: 'owned',
      bgg_objectid: '133473',
    },
    {
      id: 201,
      name: 'Tension: The Crazy Naming Game',
      player_count: '4',
      play_time: '40',
      category: '',
      personal_rating: '',
      bgg_rating: '5.91',
      status: 'owned',
      bgg_objectid: '12920',
    },
    {
      id: 202,
      name: 'This War of Mine: The Board Game',
      player_count: '1-6',
      play_time: '45-120',
      category: '',
      personal_rating: '',
      bgg_rating: '7.75',
      status: 'owned',
      bgg_objectid: '188920',
    },
    {
      id: 203,
      name: 'Through the Ages: A New Story of Civilization',
      player_count: '2-4',
      play_time: '120',
      category: '',
      personal_rating: '',
      bgg_rating: '8.24',
      status: 'owned',
      bgg_objectid: '182028',
    },
    {
      id: 204,
      name: 'Ticket to Ride',
      player_count: '2-5',
      play_time: '30-60',
      category: '',
      personal_rating: '8',
      bgg_rating: '7.38',
      status: 'owned',
      bgg_objectid: '9209',
    },
    {
      id: 205,
      name: 'Ticket to Ride Map Collection 5: United Kingdom & Pennsylvania',
      player_count: '2-5',
      play_time: '30-75',
      category: '',
      personal_rating: '7',
      bgg_rating: '7.98',
      status: 'owned',
      bgg_objectid: '182078',
    },
    {
      id: 206,
      name: 'Ticket to Ride: Europa 1912',
      player_count: '2-5',
      play_time: '30-60',
      category: '',
      personal_rating: '8',
      bgg_rating: '7.63',
      status: 'owned',
      bgg_objectid: '53383',
    },
    {
      id: 207,
      name: 'Ticket to Ride: Europe',
      player_count: '2-5',
      play_time: '30-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.52',
      status: 'owned',
      bgg_objectid: '14996',
    },
    {
      id: 208,
      name: 'Ticket to Ride: Europe – 15th Anniversary',
      player_count: '2-5',
      play_time: '30-60',
      category: '',
      personal_rating: '7.5',
      bgg_rating: '8.18',
      status: 'owned',
      bgg_objectid: '329841',
    },
    {
      id: 209,
      name: 'Ticket to Ride: USA 1910',
      player_count: '2-5',
      play_time: '30-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.99',
      status: 'owned',
      bgg_objectid: '24439',
    },
    {
      id: 210,
      name: 'Tiny Epic Defenders (Second Edition)',
      player_count: '1-4',
      play_time: '30-60',
      category: '',
      personal_rating: '',
      bgg_rating: '6.91',
      status: 'owned',
      bgg_objectid: '238656',
    },
    {
      id: 211,
      name: 'Tiny Epic Defenders (Second Edition): Deluxe Edition',
      player_count: '1-4',
      play_time: '30-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.13',
      status: 'owned',
      bgg_objectid: '316182',
    },
    {
      id: 212,
      name: 'Tiny Epic Defenders: The Dark War',
      player_count: '1-4',
      play_time: '20-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.38',
      status: 'owned',
      bgg_objectid: '228935',
    },
    {
      id: 213,
      name: 'Tiny Epic Defenders: The Dark War – Deluxe Edition',
      player_count: '1-4',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '7.49',
      status: 'owned',
      bgg_objectid: '316179',
    },
    {
      id: 214,
      name: 'ToeShamBo',
      player_count: '2',
      play_time: '5-10',
      category: '',
      personal_rating: '',
      bgg_rating: '4.84',
      status: 'owned',
      bgg_objectid: '258723',
    },
    {
      id: 215,
      name: 'Trash Pandas',
      player_count: '2-4',
      play_time: '15-20',
      category: '',
      personal_rating: '',
      bgg_rating: '6.5',
      status: 'owned (for trade)',
      bgg_objectid: '216439',
    },
    {
      id: 216,
      name: 'Treasure Island',
      player_count: '2-5',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '7.2',
      status: 'owned',
      bgg_objectid: '242639',
    },
    {
      id: 217,
      name: 'Trio',
      player_count: '3-6',
      play_time: '15',
      category: '',
      personal_rating: '',
      bgg_rating: '7.39',
      status: 'owned',
      bgg_objectid: '352515',
    },
    {
      id: 218,
      name: 'Trivial Pursuit: 20th Anniversary Edition',
      player_count: '2-6',
      play_time: '180',
      category: '',
      personal_rating: '',
      bgg_rating: '5.23',
      status: 'owned',
      bgg_objectid: '4492',
    },
    {
      id: 219,
      name: 'Turnip',
      player_count: '3-5',
      play_time: '15-30',
      category: '',
      personal_rating: '',
      bgg_rating: '6.34',
      status: 'owned',
      bgg_objectid: '421314',
    },
    {
      id: 220,
      name: 'Twister',
      player_count: '2-4',
      play_time: '10',
      category: '',
      personal_rating: '',
      bgg_rating: '4.56',
      status: 'owned',
      bgg_objectid: '5894',
    },
    {
      id: 221,
      name: 'Ultimate Werewolf',
      player_count: '5-30',
      play_time: '30-90',
      category: '',
      personal_rating: '',
      bgg_rating: '6.53',
      status: 'owned',
      bgg_objectid: '152241',
    },
    {
      id: 222,
      name: 'Ultra Tiny Epic Galaxies',
      player_count: '1-5',
      play_time: '30-45',
      category: '',
      personal_rating: '',
      bgg_rating: '7.3',
      status: 'owned (for trade)',
      bgg_objectid: '285826',
    },
    {
      id: 223,
      name: 'Under Falling Skies',
      player_count: '1',
      play_time: '20-40',
      category: '',
      personal_rating: '',
      bgg_rating: '7.59',
      status: 'owned',
      bgg_objectid: '306735',
    },
    {
      id: 224,
      name: 'Unmatched: Cobble & Fog',
      player_count: '2-4',
      play_time: '20-40',
      category: '',
      personal_rating: '',
      bgg_rating: '7.92',
      status: 'owned',
      bgg_objectid: '294484',
    },
    {
      id: 225,
      name: 'Unmatched: Houdini vs. The Genie',
      player_count: '2',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '8.2',
      status: 'owned',
      bgg_objectid: '354544',
    },
    {
      id: 226,
      name: 'Unmatched: Little Red Riding Hood vs. Beowulf',
      player_count: '2',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '8.05',
      status: 'owned',
      bgg_objectid: '325635',
    },
    {
      id: 227,
      name: 'Unmatched: Robin Hood vs. Bigfoot',
      player_count: '2',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.9',
      status: 'owned',
      bgg_objectid: '274638',
    },
    {
      id: 228,
      name: 'Unsolved Case Files: Avery & Zoey Gardner',
      player_count: '1-8',
      play_time: '180',
      category: '',
      personal_rating: '',
      bgg_rating: '7.11',
      status: 'owned (for trade)',
      bgg_objectid: '342283',
    },
    {
      id: 229,
      name: 'Unsolved Case Files: Harmony Ashcroft',
      player_count: '1-8',
      play_time: '30-120',
      category: '',
      personal_rating: '',
      bgg_rating: '6.79',
      status: 'owned',
      bgg_objectid: '313467',
    },
    {
      id: 230,
      name: 'Untold: Adventures Await',
      player_count: '1-4',
      play_time: '45-60',
      category: '',
      personal_rating: '5',
      bgg_rating: '6.73',
      status: 'owned',
      bgg_objectid: '226588',
    },
    {
      id: 231,
      name: 'Villagers',
      player_count: '1-5',
      play_time: '30-60',
      category: '',
      personal_rating: '6',
      bgg_rating: '7.1',
      status: 'owned',
      bgg_objectid: '241724',
    },
    {
      id: 232,
      name: 'War of the Ring: The Card Game',
      player_count: '2-4',
      play_time: '90-120',
      category: '',
      personal_rating: '',
      bgg_rating: '7.59',
      status: 'owned',
      bgg_objectid: '362944',
    },
    {
      id: 233,
      name: 'Wayfarers of the South Tigris',
      player_count: '1-4',
      play_time: '60-90',
      category: '',
      personal_rating: '',
      bgg_rating: '7.76',
      status: 'owned',
      bgg_objectid: '350316',
    },
    {
      id: 234,
      name: 'Welcome To...',
      player_count: '1-100',
      play_time: '25',
      category: '',
      personal_rating: '',
      bgg_rating: '7.5',
      status: 'owned',
      bgg_objectid: '233867',
    },
    {
      id: 235,
      name: 'Whitehall Mystery',
      player_count: '2-4',
      play_time: '45-60',
      category: '',
      personal_rating: '',
      bgg_rating: '7.51',
      status: 'owned',
      bgg_objectid: '190082',
    },
    {
      id: 236,
      name: 'Wild Space',
      player_count: '1-5',
      play_time: '15-40',
      category: '',
      personal_rating: '',
      bgg_rating: '7.13',
      status: 'owned',
      bgg_objectid: '298371',
    },
    {
      id: 237,
      name: 'Wildstyle',
      player_count: '2-5',
      play_time: '40',
      category: '',
      personal_rating: '',
      bgg_rating: '7.04',
      status: 'owned',
      bgg_objectid: '366782',
    },
    {
      id: 238,
      name: 'Wingspan',
      player_count: '1-5',
      play_time: '40-70',
      category: '',
      personal_rating: '',
      bgg_rating: '7.99',
      status: 'owned',
      bgg_objectid: '266192',
    },
    {
      id: 239,
      name: 'Wingspan Asia',
      player_count: '1-2',
      play_time: '40-70',
      category: '',
      personal_rating: '',
      bgg_rating: '8.21',
      status: 'owned',
      bgg_objectid: '366161',
    },
    {
      id: 240,
      name: 'Wingspan: European Expansion',
      player_count: '1-5',
      play_time: '40-70',
      category: '',
      personal_rating: '',
      bgg_rating: '8.32',
      status: 'owned',
      bgg_objectid: '290448',
    },
    {
      id: 241,
      name: 'Wingspan: Oceania Expansion',
      player_count: '1-5',
      play_time: '40-70',
      category: '',
      personal_rating: '',
      bgg_rating: '8.45',
      status: 'owned',
      bgg_objectid: '300580',
    },
    {
      id: 242,
      name: 'Wizard',
      player_count: '3-6',
      play_time: '45',
      category: '',
      personal_rating: '',
      bgg_rating: '7.01',
      status: 'owned',
      bgg_objectid: '1465',
    },
    {
      id: 243,
      name: 'Wizard School',
      player_count: '2-5',
      play_time: '40-90',
      category: '',
      personal_rating: '',
      bgg_rating: '4.76',
      status: 'owned',
      bgg_objectid: '185154',
    },
    {
      id: 244,
      name: 'Yahtzee',
      player_count: '2-10',
      play_time: '30',
      category: '',
      personal_rating: '',
      bgg_rating: '5.56',
      status: 'owned',
      bgg_objectid: '2243',
    },
    {
      id: 245,
      name: 'Zombie Kidz Evolution',
      player_count: '2-4',
      play_time: '15',
      category: '',
      personal_rating: '6.5',
      bgg_rating: '7.56',
      status: 'owned',
      bgg_objectid: '256952',
    },
    {
      id: 246,
      name: 'Zombie Teenz Evolution',
      player_count: '2-4',
      play_time: '20',
      category: '',
      personal_rating: '',
      bgg_rating: '7.6',
      status: 'owned',
      bgg_objectid: '310448',
    },
  ])
}
