export async function seed(knex) {
  await knex('boardgames').del()
  await knex('boardgames').insert([
    { id: 1, name: '5-Minute Dungeon', player_count: '2-5', play_time: '5-30', category: '', personal_rating: '', bgg_rating: '6.89', status: 'owned (for trade)' },
    { id: 2, name: '6 nimmt! 25 Jahre', player_count: '2-10', play_time: '45', category: '', personal_rating: '', bgg_rating: '7.24', status: 'owned' },
    { id: 3, name: '7 Wonders Duel', player_count: '2', play_time: '30', category: '', personal_rating: '', bgg_rating: '8.07', status: 'owned' },
    { id: 4, name: 'Adventure Land', player_count: '2-4', play_time: '45', category: '', personal_rating: '', bgg_rating: '6.89', status: 'owned (for trade)' },
    { id: 5, name: 'The Adventures of Robin Hood', player_count: '2-4', play_time: '60', category: '', personal_rating: '', bgg_rating: '7.41', status: 'owned' },
    { id: 6, name: 'Ankh\'or', player_count: '2-4', play_time: '30', category: '', personal_rating: '', bgg_rating: '6.86', status: 'owned (for trade)' },
    { id: 7, name: 'Arboretum', player_count: '2-4', play_time: '30', category: '', personal_rating: '', bgg_rating: '7.24', status: 'owned' },
    { id: 8, name: 'Back to the Future: Back in Time', player_count: '2-4', play_time: '50', category: '', personal_rating: '', bgg_rating: '7.16', status: 'owned' },
    { id: 9, name: 'Back to the Future: Dice Through Time', player_count: '2-4', play_time: '45-60', category: '', personal_rating: '', bgg_rating: '6.64', status: 'owned' },
    { id: 10, name: 'Balderdash', player_count: '2-6', play_time: '60', category: '', personal_rating: '', bgg_rating: '6.48', status: 'owned' },
    { id: 11, name: 'Bananagrams', player_count: '1-8', play_time: '15', category: '', personal_rating: '', bgg_rating: '6.43', status: 'owned' },
    { id: 12, name: 'Battleship: Card Game', player_count: '2', play_time: '15', category: '', personal_rating: '5.5', bgg_rating: '5.89', status: 'owned' },
    { id: 13, name: 'Bears vs Babies', player_count: '2-5', play_time: '15-20', category: '', personal_rating: '6', bgg_rating: '5.37', status: 'owned' },
    { id: 14, name: 'Betrayal at House on the Hill', player_count: '3-6', play_time: '60', category: '', personal_rating: '', bgg_rating: '7.01', status: 'owned' },
    { id: 15, name: 'Beyond Baker Street', player_count: '2-4', play_time: '30', category: '', personal_rating: '', bgg_rating: '6.8', status: 'owned' },
    { id: 16, name: 'BONK', player_count: '2-4', play_time: '10', category: '', personal_rating: '6.5', bgg_rating: '6.61', status: 'owned (for trade)' },
    { id: 17, name: 'Books of Time', player_count: '1-4', play_time: '45-60', category: '', personal_rating: '', bgg_rating: '7.06', status: 'owned' },
    { id: 18, name: 'Brass: Lancashire', player_count: '2-4', play_time: '60-120', category: '', personal_rating: '', bgg_rating: '8.2', status: 'owned' },
    { id: 19, name: 'Break the Safe', player_count: '2-4', play_time: '30', category: '', personal_rating: '7', bgg_rating: '6.08', status: 'owned' },
    { id: 20, name: 'Café', player_count: '1-4', play_time: '20-45', category: '', personal_rating: '7', bgg_rating: '7.14', status: 'owned' },
    { id: 21, name: 'Calico', player_count: '1-4', play_time: '30-45', category: '', personal_rating: '', bgg_rating: '7.47', status: 'owned' },
    { id: 22, name: 'Carcassonne: Hunters and Gatherers', player_count: '2-5', play_time: '35-40', category: '', personal_rating: '9', bgg_rating: '7.13', status: 'owned' },
    { id: 23, name: 'Carcassonne: South Seas', player_count: '2-5', play_time: '35', category: '', personal_rating: '', bgg_rating: '7.05', status: 'owned' },
    { id: 24, name: 'Carcassonne: The Discovery', player_count: '2-5', play_time: '30-45', category: '', personal_rating: '7', bgg_rating: '6.48', status: 'owned' },
    { id: 25, name: 'Cards Against Humanity: Family Edition', player_count: '4-30', play_time: '30', category: '', personal_rating: '6.5', bgg_rating: '6.1', status: 'owned' },
    { id: 26, name: 'The Castles of Burgundy', player_count: '2-4', play_time: '30-90', category: '', personal_rating: '', bgg_rating: '8.16', status: 'owned' },
    { id: 27, name: 'Catan', player_count: '3-4', play_time: '60-120', category: '', personal_rating: '7', bgg_rating: '7.09', status: 'owned' },
    { id: 28, name: 'Century: Golem Edition', player_count: '2-5', play_time: '30-45', category: '', personal_rating: '8', bgg_rating: '7.57', status: 'owned' },
    { id: 29, name: 'Chess', player_count: '2', play_time: '', category: '', personal_rating: '8', bgg_rating: '7.24', status: 'owned' },
    { id: 30, name: 'Chronicles of Crime', player_count: '1-4', play_time: '60-90', category: '', personal_rating: '', bgg_rating: '7.53', status: 'owned' },
    { id: 31, name: 'Chronicles of Crime: 1400', player_count: '1-4', play_time: '60-90', category: '', personal_rating: '', bgg_rating: '7.68', status: 'owned' },
    { id: 32, name: 'Chronicles of Crime: 1900', player_count: '1-4', play_time: '60-90', category: '', personal_rating: '8', bgg_rating: '7.88', status: 'owned' },
    { id: 33, name: 'Chronicles of Crime: 2400', player_count: '1-4', play_time: '60-90', category: '', personal_rating: '', bgg_rating: '7.6', status: 'owned' },
    { id: 34, name: 'Cinco Linko', player_count: '2-4', play_time: '5-15', category: '', personal_rating: '', bgg_rating: '6.59', status: 'owned' },
    { id: 35, name: 'Circadians: First Light', player_count: '1-4', play_time: '60-90', category: '', personal_rating: '', bgg_rating: '7.51', status: 'owned' },
    { id: 36, name: 'Citadels', player_count: '2-8', play_time: '30-60', category: '', personal_rating: '7', bgg_rating: '7.23', status: 'owned' },
    { id: 37, name: 'Clank!: A Deck-Building Adventure', player_count: '2-4', play_time: '30-60', category: '', personal_rating: '7', bgg_rating: '7.76', status: 'owned' },
    { id: 38, name: 'Clash of Decks: Starter Kit', player_count: '1-2', play_time: '15-30', category: '', personal_rating: '', bgg_rating: '6.28', status: 'owned' },
    { id: 39, name: 'Clue', player_count: '2-6', play_time: '45', category: '', personal_rating: '', bgg_rating: '5.69', status: 'owned' },
    { id: 40, name: 'Clue: Treachery at Tudor Mansion', player_count: '1-6', play_time: '90', category: '', personal_rating: '', bgg_rating: '6.31', status: 'owned' },
    { id: 41, name: 'Cobras', player_count: '1-5', play_time: '30-45', category: '', personal_rating: '', bgg_rating: '6.8', status: 'owned' },
    { id: 42, name: 'Coloretto', player_count: '2-5', play_time: '30', category: '', personal_rating: '7.5', bgg_rating: '6.98', status: 'owned' },
    { id: 43, name: 'Colt Express', player_count: '2-6', play_time: '40', category: '', personal_rating: '', bgg_rating: '7.1', status: 'owned' },
    { id: 44, name: 'Confident?', player_count: '3-99', play_time: '20-40', category: '', personal_rating: '7', bgg_rating: '6.61', status: 'owned' },
    { id: 45, name: 'Coup', player_count: '2-6', play_time: '15', category: '', personal_rating: '', bgg_rating: '6.98', status: 'owned' },
    { id: 46, name: 'The Crew: The Quest for Planet Nine', player_count: '2-5', play_time: '20', category: '', personal_rating: '', bgg_rating: '7.75', status: 'owned' },
    { id: 47, name: 'Crimopolis', player_count: '2-5', play_time: '30-100', category: '', personal_rating: '', bgg_rating: '7.12', status: 'owned (for trade)' },
    { id: 48, name: 'Crown of Emara', player_count: '1-4', play_time: '45-75', category: '', personal_rating: '', bgg_rating: '7.34', status: 'owned' },
    { id: 49, name: 'Decrypto', player_count: '3-8', play_time: '15-45', category: '', personal_rating: '7', bgg_rating: '7.76', status: 'owned' },
    { id: 50, name: 'Dominion: Second Edition', player_count: '2-4', play_time: '30', category: '', personal_rating: '', bgg_rating: '7.82', status: 'owned' },
    { id: 51, name: 'Don\'t Get Got!', player_count: '2-10', play_time: '', category: '', personal_rating: '', bgg_rating: '6.92', status: 'owned (for trade)' },
    { id: 52, name: 'Downspin', player_count: '2', play_time: '30', category: '', personal_rating: '6.5', bgg_rating: '5.53', status: 'owned' },
    { id: 53, name: 'Dungeons & Dragons Starter Set', player_count: '2-6', play_time: '60', category: '', personal_rating: '', bgg_rating: '7.69', status: 'owned' },
    { id: 54, name: 'E.T. The Extra-Terrestrial: Light Years From Home Game', player_count: '2-4', play_time: '30', category: '', personal_rating: '', bgg_rating: '6.79', status: 'owned (for trade)' },
    { id: 55, name: 'Evolution', player_count: '2-6', play_time: '60', category: '', personal_rating: '7', bgg_rating: '7', status: 'owned' },
    { id: 56, name: 'Exploding Kittens', player_count: '2-5', play_time: '15', category: '', personal_rating: '6.5', bgg_rating: '6.07', status: 'owned' },
    { id: 57, name: 'Fleet: The Dice Game (Second Edition)', player_count: '1-4', play_time: '30-45', category: '', personal_rating: '', bgg_rating: '7.72', status: 'owned' },
    { id: 58, name: 'Foosketball', player_count: '1-2', play_time: '5-15', category: '', personal_rating: '', bgg_rating: '6.12', status: 'owned' },
    { id: 59, name: 'For Sale', player_count: '3-6', play_time: '30', category: '', personal_rating: '', bgg_rating: '7.27', status: 'owned' },
    { id: 60, name: 'Fort', player_count: '2-4', play_time: '20-40', category: '', personal_rating: '', bgg_rating: '7.05', status: 'owned' },
    { id: 61, name: 'The Fox in the Forest', player_count: '2', play_time: '30', category: '', personal_rating: '', bgg_rating: '7.05', status: 'owned' },
    { id: 62, name: 'Funkoverse Strategy Game: Jurassic Park 100', player_count: '2-4', play_time: '20-60', category: '', personal_rating: '', bgg_rating: '7.06', status: 'owned (for trade)' },
    { id: 63, name: 'The Game: Face to Face', player_count: '2', play_time: '20', category: '', personal_rating: '', bgg_rating: '7.04', status: 'owned' },
    { id: 64, name: 'Gloom', player_count: '2-5', play_time: '60', category: '', personal_rating: '', bgg_rating: '6.33', status: 'owned' },
    { id: 65, name: 'Granny Wars:  A Game of Tit for Tat', player_count: '2-8', play_time: '20', category: '', personal_rating: '', bgg_rating: '6.16', status: 'owned (for trade)' },
    { id: 66, name: 'Great Western Trail: New Zealand', player_count: '1-4', play_time: '75-150', category: '', personal_rating: '', bgg_rating: '8.45', status: 'owned' },
    { id: 67, name: 'Groundhog Day: The Game', player_count: '2-6', play_time: '15-25', category: '', personal_rating: '', bgg_rating: '7.18', status: 'owned' },
    { id: 68, name: 'Guess Who?', player_count: '2', play_time: '20', category: '', personal_rating: '', bgg_rating: '4.86', status: 'owned' },
    { id: 69, name: 'Guess Who?: Card Game', player_count: '2', play_time: '', category: '', personal_rating: '', bgg_rating: '4.76', status: 'owned' },
    { id: 70, name: 'Hanabi', player_count: '2-5', play_time: '25', category: '', personal_rating: '', bgg_rating: '7.03', status: 'owned' },
    { id: 71, name: 'Heat: Pedal to the Metal', player_count: '1-6', play_time: '30-60', category: '', personal_rating: '', bgg_rating: '7.99', status: 'owned' },
    { id: 72, name: 'Hive', player_count: '2', play_time: '20', category: '', personal_rating: '8', bgg_rating: '7.31', status: 'owned' },
    { id: 73, name: 'The Hunger', player_count: '2-6', play_time: '60', category: '', personal_rating: '', bgg_rating: '6.99', status: 'owned' },
    { id: 74, name: 'Infinity Gauntlet: A Love Letter Game', player_count: '2-6', play_time: '15', category: '', personal_rating: '', bgg_rating: '6.91', status: 'owned' },
    { id: 75, name: 'It\'s a Wonderful Kingdom', player_count: '1-2', play_time: '45', category: '', personal_rating: '', bgg_rating: '7.05', status: 'owned' },
    { id: 76, name: 'IUNU', player_count: '2-4', play_time: '30', category: '', personal_rating: '', bgg_rating: '6.62', status: 'owned' },
    { id: 77, name: 'Jaipur', player_count: '2', play_time: '30', category: '', personal_rating: '', bgg_rating: '7.48', status: 'owned' },
    { id: 78, name: 'Jane Austen\'s Matchmaker', player_count: '3-6', play_time: '30', category: '', personal_rating: '', bgg_rating: '6.3', status: 'owned' },
    { id: 79, name: 'Jungle Speed', player_count: '2-10', play_time: '10', category: '', personal_rating: '', bgg_rating: '6.45', status: 'owned' },
    { id: 80, name: 'Kalah', player_count: '2', play_time: '10', category: '', personal_rating: '', bgg_rating: '6.02', status: 'owned' },
    { id: 81, name: 'Kids Chronicles: Quest for the Moon Stones', player_count: '1-4', play_time: '30-45', category: '', personal_rating: '', bgg_rating: '7.22', status: 'owned' },
    { id: 82, name: 'Kill The Unicorns', player_count: '3-6', play_time: '25-45', category: '', personal_rating: '', bgg_rating: '6.81', status: 'owned' },
    { id: 83, name: 'King of Tokyo: Dark Edition', player_count: '2-6', play_time: '30', category: '', personal_rating: '7.5', bgg_rating: '7.64', status: 'owned' },
    { id: 84, name: 'Kingdomino', player_count: '2-4', play_time: '15-25', category: '', personal_rating: '', bgg_rating: '7.29', status: 'owned' },
    { id: 85, name: 'Kingdomino Origins', player_count: '2-4', play_time: '20-40', category: '', personal_rating: '', bgg_rating: '7.44', status: 'owned' },
    { id: 86, name: 'KLASK', player_count: '2', play_time: '10', category: '', personal_rating: '', bgg_rating: '7.62', status: 'owned' },
    { id: 87, name: 'Legacy of Yu', player_count: '1', play_time: '60', category: '', personal_rating: '', bgg_rating: '8.07', status: 'owned' },
    { id: 88, name: 'Llamas Unleashed', player_count: '2-8', play_time: '30-45', category: '', personal_rating: '', bgg_rating: '6.09', status: 'owned' },
    { id: 89, name: 'Loot', player_count: '2-8', play_time: '20', category: '', personal_rating: '6', bgg_rating: '6.3', status: 'owned' },
    { id: 90, name: 'Lost Cities', player_count: '2', play_time: '30', category: '', personal_rating: '8', bgg_rating: '7.26', status: 'owned' },
    { id: 91, name: 'Lost Cities: Rivals', player_count: '2-4', play_time: '40', category: '', personal_rating: '', bgg_rating: '6.65', status: 'owned (for trade)' },
    { id: 92, name: 'Lost Ruins of Arnak', player_count: '1-4', play_time: '30-120', category: '', personal_rating: '8', bgg_rating: '8.08', status: 'owned' },
    { id: 93, name: 'Love Letter', player_count: '2-4', play_time: '20', category: '', personal_rating: '', bgg_rating: '7.23', status: 'owned' },
    { id: 94, name: 'Love Letter', player_count: '2-6', play_time: '20', category: '', personal_rating: '', bgg_rating: '7.5', status: 'owned' },
    { id: 95, name: 'Love Letter: Adventure Time', player_count: '2-4', play_time: '20', category: '', personal_rating: '', bgg_rating: '7.27', status: 'owned' },
    { id: 96, name: 'Mariposas', player_count: '2-5', play_time: '45-75', category: '', personal_rating: '', bgg_rating: '6.73', status: 'owned' },
    { id: 97, name: 'Medium', player_count: '2-8', play_time: '30-45', category: '', personal_rating: '', bgg_rating: '6.82', status: 'owned' },
    { id: 98, name: 'The Mind', player_count: '2-4', play_time: '20', category: '', personal_rating: '7', bgg_rating: '6.71', status: 'owned' },
    { id: 99, name: 'Most Wanted', player_count: '2-8', play_time: '15-35', category: '', personal_rating: '', bgg_rating: '6.5', status: 'owned' },
    { id: 100, name: 'Mountain of Inferno', player_count: '2-4', play_time: '25', category: '', personal_rating: '', bgg_rating: '5.63', status: 'owned (for trade)' },
    { id: 101, name: 'Muffin Time', player_count: '2-8', play_time: '20-40', category: '', personal_rating: '', bgg_rating: '6.2', status: 'owned' },
    { id: 102, name: 'Murder Mystery Party: A Taste for Wine and Murder', player_count: '6-8', play_time: '180', category: '', personal_rating: '', bgg_rating: '6.52', status: 'owned' },
    { id: 103, name: 'Murder Mystery Party: Pasta, Passion & Pistols', player_count: '6-8', play_time: '180', category: '', personal_rating: '', bgg_rating: '5.91', status: 'owned' },
    { id: 104, name: 'Neuroshima Hex', player_count: '2-4', play_time: '30', category: '', personal_rating: '', bgg_rating: '7.38', status: 'owned (for trade)' },
    { id: 105, name: 'Nidavellir', player_count: '2-5', play_time: '45', category: '', personal_rating: '', bgg_rating: '7.55', status: 'owned' },
    { id: 106, name: 'Nightmare', player_count: '3-6', play_time: '60', category: '', personal_rating: '', bgg_rating: '5.96', status: 'owned' },
    { id: 107, name: 'No Thanks!', player_count: '3-7', play_time: '20', category: '', personal_rating: '', bgg_rating: '7.08', status: 'owned' },
    { id: 108, name: 'Oath', player_count: '1-6', play_time: '45-150', category: '', personal_rating: '', bgg_rating: '7.7', status: 'owned' },
    { id: 109, name: 'One Night Ultimate Alien', player_count: '4-10', play_time: '10', category: '', personal_rating: '', bgg_rating: '6.89', status: 'owned' },
    { id: 110, name: 'One Night Ultimate Vampire', player_count: '3-10', play_time: '10', category: '', personal_rating: '', bgg_rating: '6.65', status: 'owned' },
    { id: 111, name: 'One Night Ultimate Werewolf', player_count: '3-10', play_time: '10', category: '', personal_rating: '8.5', bgg_rating: '7.03', status: 'owned' },
    { id: 112, name: 'Othello', player_count: '2', play_time: '30', category: '', personal_rating: '', bgg_rating: '6.16', status: 'owned' },
    { id: 113, name: 'Otys', player_count: '1-4', play_time: '60', category: '', personal_rating: '', bgg_rating: '6.94', status: 'owned' },
    { id: 114, name: 'Paladins of the West Kingdom', player_count: '1-4', play_time: '90-120', category: '', personal_rating: '', bgg_rating: '7.95', status: 'owned' },
    { id: 115, name: 'Parade', player_count: '2-6', play_time: '45', category: '', personal_rating: '', bgg_rating: '7', status: 'owned' },
    { id: 116, name: 'Parks', player_count: '1-5', play_time: '30-60', category: '', personal_rating: '', bgg_rating: '7.61', status: 'owned (for trade)' },
    { id: 117, name: 'Patchwork', player_count: '2', play_time: '15-30', category: '', personal_rating: '', bgg_rating: '7.58', status: 'owned' },
    { id: 118, name: 'Pendulum', player_count: '1-5', play_time: '60-90', category: '', personal_rating: '', bgg_rating: '6.38', status: 'owned' },
    { id: 119, name: 'Phase 10', player_count: '2-6', play_time: '45', category: '', personal_rating: '', bgg_rating: '5.29', status: 'owned' },
    { id: 120, name: 'Pictionary', player_count: '3-16', play_time: '90', category: '', personal_rating: '', bgg_rating: '5.86', status: 'owned' },
    { id: 121, name: 'Pictureka!', player_count: '2-7', play_time: '30', category: '', personal_rating: '', bgg_rating: '5.5', status: 'owned' },
    { id: 122, name: 'Pictures', player_count: '3-5', play_time: '20-30', category: '', personal_rating: '', bgg_rating: '7.22', status: 'owned' },
    { id: 123, name: 'Point Salad', player_count: '2-6', play_time: '15-30', category: '', personal_rating: '', bgg_rating: '7.08', status: 'owned (for trade)' },
    { id: 124, name: 'Police Precinct', player_count: '1-6', play_time: '90', category: '', personal_rating: '', bgg_rating: '6.84', status: 'owned' },
    { id: 125, name: 'Project L', player_count: '1-4', play_time: '20-40', category: '', personal_rating: '', bgg_rating: '7.44', status: 'owned' },
    { id: 126, name: 'Puerto Rico', player_count: '2-5', play_time: '90-150', category: '', personal_rating: '', bgg_rating: '8.3', status: 'owned' },
    { id: 127, name: 'Quacks', player_count: '2-4', play_time: '45', category: '', personal_rating: '8', bgg_rating: '7.8', status: 'owned' },
    { id: 128, name: 'Qwirkle', player_count: '2-4', play_time: '45', category: '', personal_rating: '', bgg_rating: '6.77', status: 'owned' },
    { id: 129, name: 'Race for the Galaxy', player_count: '2-4', play_time: '30-60', category: '', personal_rating: '', bgg_rating: '7.74', status: 'owned' },
    { id: 130, name: 'Raid the Pantry', player_count: '2-4', play_time: '30', category: '', personal_rating: '', bgg_rating: '7.03', status: 'owned' },
    { id: 131, name: 'Raiders of Scythia', player_count: '1-4', play_time: '60-80', category: '', personal_rating: '', bgg_rating: '7.69', status: 'owned' },
    { id: 132, name: 'Raiders of the North Sea', player_count: '2-4', play_time: '60-80', category: '', personal_rating: '', bgg_rating: '7.72', status: 'owned' },
    { id: 133, name: 'Regicide', player_count: '1-4', play_time: '10-30', category: '', personal_rating: '', bgg_rating: '7.39', status: 'owned' },
    { id: 134, name: 'Reign of Cthulhu', player_count: '2-4', play_time: '40', category: '', personal_rating: '', bgg_rating: '7.36', status: 'owned' },
    { id: 135, name: 'Risk Legacy', player_count: '3-5', play_time: '60', category: '', personal_rating: '', bgg_rating: '7.35', status: 'owned' },
    { id: 136, name: 'Rivals for Catan', player_count: '2', play_time: '45-60', category: '', personal_rating: '', bgg_rating: '6.93', status: 'owned (for trade)' },
    { id: 137, name: 'The Rocketeer: Fate of the Future', player_count: '2', play_time: '45', category: '', personal_rating: '', bgg_rating: '7', status: 'owned' },
    { id: 138, name: 'Root', player_count: '2-4', play_time: '60-90', category: '', personal_rating: '', bgg_rating: '8.07', status: 'owned' },
    { id: 139, name: 'Rubik\'s Race', player_count: '2', play_time: '5', category: '', personal_rating: '', bgg_rating: '6.06', status: 'owned' },
    { id: 140, name: 'Rummikub', player_count: '2-4', play_time: '60', category: '', personal_rating: '', bgg_rating: '6.53', status: 'owned' },
    { id: 141, name: 'San Juan', player_count: '2-4', play_time: '45-60', category: '', personal_rating: '', bgg_rating: '7.23', status: 'owned' },
    { id: 142, name: 'Santorini', player_count: '2-4', play_time: '20', category: '', personal_rating: '7.5', bgg_rating: '7.33', status: 'owned' },
    { id: 143, name: 'Scattergories', player_count: '2-6', play_time: '30', category: '', personal_rating: '', bgg_rating: '6.31', status: 'owned' },
    { id: 144, name: 'Scrabble', player_count: '2-4', play_time: '90', category: '', personal_rating: '', bgg_rating: '6.28', status: 'owned' },
    { id: 145, name: 'The Search for Planet X', player_count: '1-4', play_time: '60-75', category: '', personal_rating: '', bgg_rating: '7.89', status: 'owned' },
    { id: 146, name: 'Sherlock Holmes Consulting Detective: The Baker Street Irregulars', player_count: '1-8', play_time: '90', category: '', personal_rating: '', bgg_rating: '8.16', status: 'owned' },
    { id: 147, name: 'Side Quest: Frostpunk', player_count: '1-4', play_time: '60-90', category: '', personal_rating: '', bgg_rating: '6.57', status: 'owned (for trade)' },
    { id: 148, name: 'Soda Smugglers', player_count: '3-8', play_time: '20', category: '', personal_rating: '', bgg_rating: '6.7', status: 'owned' },
    { id: 149, name: 'Sparkle*Kitty', player_count: '3-8', play_time: '10-20', category: '', personal_rating: '', bgg_rating: '6.25', status: 'owned' },
    { id: 150, name: 'Spirit Island', player_count: '1-4', play_time: '90-120', category: '', personal_rating: '', bgg_rating: '8.34', status: 'owned' },
    { id: 151, name: 'Splendor', player_count: '2-4', play_time: '30', category: '', personal_rating: '9', bgg_rating: '7.42', status: 'owned' },
    { id: 152, name: 'Splendor Duel', player_count: '2', play_time: '30', category: '', personal_rating: '6', bgg_rating: '7.88', status: 'owned' },
    { id: 153, name: 'Star Wars: Jabba\'s Palace – A Love Letter Game', player_count: '2-6', play_time: '20', category: '', personal_rating: '', bgg_rating: '7.19', status: 'owned' },
    { id: 154, name: 'Struggle for Catan', player_count: '2-4', play_time: '30', category: '', personal_rating: '', bgg_rating: '6.17', status: 'owned (for trade)' },
    { id: 155, name: 'Sushi Go Party!', player_count: '2-8', play_time: '20', category: '', personal_rating: '', bgg_rating: '7.37', status: 'owned' },
    { id: 156, name: 'Sushi Go!', player_count: '2-5', play_time: '15', category: '', personal_rating: '', bgg_rating: '6.98', status: 'owned' },
    { id: 157, name: 'Tension: The Crazy Naming Game', player_count: '4', play_time: '40', category: '', personal_rating: '', bgg_rating: '5.91', status: 'owned' },
    { id: 158, name: 'This War of Mine: The Board Game', player_count: '1-6', play_time: '45-120', category: '', personal_rating: '', bgg_rating: '7.75', status: 'owned' },
    { id: 159, name: 'Through the Ages: A New Story of Civilization', player_count: '2-4', play_time: '120', category: '', personal_rating: '', bgg_rating: '8.24', status: 'owned' },
    { id: 160, name: 'Ticket to Ride', player_count: '2-5', play_time: '30-60', category: '', personal_rating: '8', bgg_rating: '7.38', status: 'owned' },
    { id: 161, name: 'Ticket to Ride: Europe', player_count: '2-5', play_time: '30-60', category: '', personal_rating: '', bgg_rating: '7.52', status: 'owned' },
    { id: 162, name: 'Ticket to Ride: Europe – 15th Anniversary', player_count: '2-5', play_time: '30-60', category: '', personal_rating: '7.5', bgg_rating: '8.18', status: 'owned' },
    { id: 163, name: 'Tiny Epic Defenders (Second Edition)', player_count: '1-4', play_time: '30-60', category: '', personal_rating: '', bgg_rating: '6.91', status: 'owned' },
    { id: 164, name: 'Tiny Epic Defenders (Second Edition): Deluxe Edition', player_count: '1-4', play_time: '30-60', category: '', personal_rating: '', bgg_rating: '7.13', status: 'owned' },
    { id: 165, name: 'ToeShamBo', player_count: '2', play_time: '5-10', category: '', personal_rating: '', bgg_rating: '4.84', status: 'owned' },
    { id: 166, name: 'Trash Pandas', player_count: '2-4', play_time: '15-20', category: '', personal_rating: '', bgg_rating: '6.5', status: 'owned (for trade)' },
    { id: 167, name: 'Treasure Island', player_count: '2-5', play_time: '45', category: '', personal_rating: '', bgg_rating: '7.2', status: 'owned' },
    { id: 168, name: 'Trio', player_count: '3-6', play_time: '15', category: '', personal_rating: '', bgg_rating: '7.39', status: 'owned' },
    { id: 169, name: 'Trivial Pursuit: 20th Anniversary Edition', player_count: '2-6', play_time: '180', category: '', personal_rating: '', bgg_rating: '5.23', status: 'owned' },
    { id: 170, name: 'Twister', player_count: '2-4', play_time: '10', category: '', personal_rating: '', bgg_rating: '4.56', status: 'owned' },
    { id: 171, name: 'Ultimate Werewolf', player_count: '5-30', play_time: '30-90', category: '', personal_rating: '', bgg_rating: '6.54', status: 'owned' },
    { id: 172, name: 'Ultra Tiny Epic Galaxies', player_count: '1-5', play_time: '30-45', category: '', personal_rating: '', bgg_rating: '7.3', status: 'owned (for trade)' },
    { id: 173, name: 'Under Falling Skies', player_count: '1', play_time: '20-40', category: '', personal_rating: '', bgg_rating: '7.59', status: 'owned' },
    { id: 174, name: 'Unmatched: Cobble & Fog', player_count: '2-4', play_time: '20-40', category: '', personal_rating: '', bgg_rating: '7.92', status: 'owned' },
    { id: 175, name: 'Unmatched: Houdini vs. The Genie', player_count: '2', play_time: '20', category: '', personal_rating: '', bgg_rating: '8.2', status: 'owned' },
    { id: 176, name: 'Unmatched: Little Red Riding Hood vs. Beowulf', player_count: '2', play_time: '20', category: '', personal_rating: '', bgg_rating: '8.05', status: 'owned' },
    { id: 177, name: 'Unsolved Case Files: Avery & Zoey Gardner', player_count: '1-8', play_time: '180', category: '', personal_rating: '', bgg_rating: '7.11', status: 'owned (for trade)' },
    { id: 178, name: 'Untold: Adventures Await', player_count: '1-4', play_time: '45-60', category: '', personal_rating: '5', bgg_rating: '6.73', status: 'owned' },
    { id: 179, name: 'Villagers', player_count: '1-5', play_time: '30-60', category: '', personal_rating: '6', bgg_rating: '7.1', status: 'owned' },
    { id: 180, name: 'War of the Ring: The Card Game', player_count: '2-4', play_time: '90-120', category: '', personal_rating: '', bgg_rating: '7.59', status: 'owned' },
    { id: 181, name: 'Wayfarers of the South Tigris', player_count: '1-4', play_time: '60-90', category: '', personal_rating: '', bgg_rating: '7.76', status: 'owned' },
    { id: 182, name: 'Welcome To...', player_count: '1-100', play_time: '25', category: '', personal_rating: '', bgg_rating: '7.5', status: 'owned' },
    { id: 183, name: 'Whitehall Mystery', player_count: '2-4', play_time: '45-60', category: '', personal_rating: '', bgg_rating: '7.51', status: 'owned' },
    { id: 184, name: 'Wild Space', player_count: '1-5', play_time: '15-40', category: '', personal_rating: '', bgg_rating: '7.13', status: 'owned' },
    { id: 185, name: 'Wildstyle', player_count: '2-5', play_time: '40', category: '', personal_rating: '', bgg_rating: '7.04', status: 'owned' },
    { id: 186, name: 'Wingspan', player_count: '1-5', play_time: '40-70', category: '', personal_rating: '', bgg_rating: '8', status: 'owned' },
    { id: 187, name: 'Wingspan Asia', player_count: '1-2', play_time: '40-70', category: '', personal_rating: '', bgg_rating: '8.21', status: 'owned' },
    { id: 188, name: 'Wizard School', player_count: '2-5', play_time: '40-90', category: '', personal_rating: '', bgg_rating: '4.76', status: 'owned' },
    { id: 189, name: 'Yahtzee', player_count: '2-10', play_time: '30', category: '', personal_rating: '', bgg_rating: '5.56', status: 'owned' },
    { id: 190, name: 'Zombie Kidz Evolution', player_count: '2-4', play_time: '15', category: '', personal_rating: '6.5', bgg_rating: '7.56', status: 'owned' },
    { id: 191, name: 'Zombie Teenz Evolution', player_count: '2-4', play_time: '20', category: '', personal_rating: '', bgg_rating: '7.6', status: 'owned' },
  ])
}